// Generated by CoffeeScript 1.10.0

/* 
KvSetParagraphTags v. 1.0.2
Adobe InDesign script
vetl1489
 */
#target InDesign
(function() {
  var arrCS1, arrPS1, arrPS2, classKill, errCounter, errMessage, main, setTag;

  errCounter = 0;

  errMessage = "";

  classKill = "kill";

  arrPS1 = [['Заголовок 18', 'h1', classKill], ['Подзаголовок в тексте', 'h3', classKill], ['Основной 8', 'p', classKill], ['Стих', 'p', 'lyric'], ['Основной 8 (буквица)', 'p', classKill], ['бе', 'p', classKill], ['Основной 8 (маркер)', 'li', classKill], ['Основной 8 (маркер точка)', 'li', classKill], ['Основной 8 (нумер 111)', 'li', classKill], ['Основной 8 (нумер 123)', 'li', classKill], ['Уважаемые', 'h4', classKill], ['Подверсток 1', 'p', classKill], ['Подверсток список', 'li', classKill], ['ЛИД', 'p', 'big'], ['Подпись', 'p', 'signed'], ['Врезка_цитата', 'div', classKill], ['foto_podp', 'div', classKill], ['foto_podp_author', 'p', classKill], ['Рубрика 1', 'div', classKill], ['Рубрика 2', 'div', classKill], ['Рубрика 3', 'div', classKill], ['Рубрика 3_2', 'div', classKill], ['Рубрика 5', 'div', classKill], ['Заголовок 48', 'h1', classKill], ['Заголовок 36', 'h1', classKill], ['Заголовок 24', 'h1', classKill], ['Подзаголовок 18', 'h2', classKill]];

  arrPS2 = [['table_L', 'p', classKill], ['table_BL', 'p', classKill], ['table_BR', 'p', classKill], ['table_C', 'p', classKill], ['table_BC', 'p', classKill], ['table_R', 'p', classKill]];

  arrCS1 = [['Точка колонтитула', 'span', classKill], ['точка маркер', 'span', classKill], ['Bold', 'strong', classKill], ['Italic', 'em', classKill], ['Выделение в тексте', 'strong', classKill], ['Буквица', 'span', classKill]];

  setTag = function(selectStyle, group, style, tag, tagClass) {
    var errOut, error, j, k, len, myStyle, ref;
    if (selectStyle == null) {
      selectStyle = "character";
    }
    try {
      if (selectStyle === "paragraph") {
        myStyle = app.activeDocument.paragraphStyleGroups.itemByName(group).paragraphStyles.itemByName(style);
      } else {
        myStyle = app.activeDocument.characterStyleGroups.itemByName(group).characterStyles.itemByName(style);
      }
      if (myStyle.styleExportTagMaps.length === 0) {
        myStyle.styleExportTagMaps.add('EPUB', tag, tagClass, '');
        myStyle.styleExportTagMaps[0].emitCss = false;
      } else {
        ref = myStyle.styleExportTagMaps.length;
        for (k = 0, len = ref.length; k < len; k++) {
          j = ref[k];
          myStyle.styleExportTagMaps[j].remove();
        }
        myStyle.styleExportTagMaps.add('EPUB', tag, tagClass, '');
        myStyle.styleExportTagMaps[0].emitCss = false;
      }
    } catch (error) {
      errOut = "Отсутствует стиль абзаца \"" + group + ": " + style + "\"";
      $.writeln(errOut);
      errCounter++;
      return errMessage = errMessage + errOut + "\n";
    }
  };

  main = function() {
    var i, k, l, len, len1, len2, m;
    for (k = 0, len = arrPS1.length; k < len; k++) {
      i = arrPS1[k];
      setTag("paragraph", "верстка", i[0], i[1], i[2]);
    }
    for (l = 0, len1 = arrPS2.length; l < len1; l++) {
      i = arrPS2[l];
      setTag("paragraph", "Таблица", i[0], i[1], i[2]);
    }
    for (m = 0, len2 = arrCS1.length; m < len2; m++) {
      i = arrCS1[m];
      setTag("character", "верстка", i[0], i[1], i[2]);
    }
    if (errCounter > 0) {
      alert("ОШИБКИ! Количество: " + errCounter + " шт.\n " + errMessage);
    } else {
      $.writeln('Готово!');
    }
    return alert('Готово!');
  };

  app.doScript(main, ScriptLanguage.JAVASCRIPT, [], UndoModes.ENTIRE_SCRIPT, "KvSetParagraphTags");

}).call(this);

//# sourceMappingURL=KvSetParagraphTags.js.map
